name: Test asdf-angular-cli plugin

on:
  push:
  pull_request:
  schedule:
    # Run weekly to show activity and catch regressions
    - cron: '0 3 * * 1'

jobs:
  test-npm:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Test asdf-angular-cli
        uses: asdf-vm/actions/plugin-test@v4
        with:
          version: 18.2.1
          command: ng --version
  
  test-pnpm:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install jq pnpm
          else
            sudo apt-get update && sudo apt-get install -y jq pnpm
          fi

      - name: Install asdf
        uses: asdf-vm/actions/setup@v4

      - name: Install asdf-angular-cli
        uses: asdf-vm/actions/plugins-add@v4
        with:
          tool_versions: angular-cli
      
      - name: Test asdf-angular-cli
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: ng --version
